### ISSUE TITLE
All your CSSi are breaking down different elements of the CSS. 

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#12]
Please use selectors well and remove all code not required for the function they were added for. If the plan was to use someone else's css, then why did we develop ours at all?

**Comment by thel3l** [comment]
Our login page cannot use the css from our main CSS doc. Geddit? Fix by ver.1.0

**Comment by lunaroyster** [comment]
I'm not talking about the login. look at the main page.

**Comment by thel3l** [comment]
Don't see anything wrong..

**Comment by lunaroyster** [comment]
Fixing it. I'm overhauling the main page
Don't worry. Gonna remake the toggle from scratch

**Comment by thel3l** [comment]
'Don't worry'... We _wanted_ material design.

**Comment by lunaroyster** [comment]
Well, learn to control it. It is peeing over all the page

**Comment by thel3l** [comment]
#pee

**Comment by thel3l** [comment]
Closed. Fixed with commit 321

**Comment by lunaroyster** [comment]
Nope. Check out the button in location for example. Inspect Element shows that scss is still affecting it. It isn't suppost to be that big.

**Comment by lunaroyster** [comment]
UPDATE: Fixed materialize.css by removing like 9000 lines of code. Don't worry. The animation still works
