### ISSUE TITLE
Map and gist delay page load

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#15]
Use some script to load on demand.

**Comment by lunaroyster** [comment]
Aren't we moving the code version to 1337?

**Comment by thel3l** [comment]
?

**Comment by rithvikvibhu** [comment]
What should i do?

**Comment by lunaroyster** [comment]
Work on the code for the map. It should not be loaded by default.

**Comment by rithvikvibhu** [comment]
cd3c521a15cd0b0268a43b014abd6e7609f4d198
