### ISSUE TITLE
Convert the logo into a flash animation?

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#17]
The Codefest logo is currently is a SVG, and is not compatible with IE or Edge (Thanks Microsoft). Should we make it a flash animation, and then require the user to have flash installed to load the page?

**Comment by thebongy** [comment]
If you are making flash a dependency in the first place, there is no need for converting the logo to a flash animation. Check out svgweb by google https://code.google.com/p/svgweb/.

**Comment by thel3l** [comment]
@thebongy @lunaroyster @rithvikvibhu 
Ye know what? @&#%$ IE. And edge. The SVG stays.

**Comment by thebongy** [comment]
Even if you do use svgweb, the SVG will stay, and you will be covered in all cases. Just some minor code changes. So why not use it? (SVGweb takes your SVG code and renders it using flash.)

**Comment by thel3l** [comment]
We'll look into it. :)

**Comment by hackdpse** [comment]
Isn't svg 2dimensional. Can't we try for 3 d?

**Comment by thebongy** [comment]
3d would either require 3d css transforms, or something like extracting a gif from a 3d graphics renderer like Blender.
