### ISSUE TITLE
The Copyright Line.

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#2]
@rithvikvibhu @lunaroyster Do you guys think that The copyright line should include **_"And those who didn't contemplate the base 3 joke."**_?

**Comment by lunaroyster** [comment]
Yup. You need a math lesson. Base 3 is a number system where 0,1,2 are the numbers. Like binary, but 3.

In base 3, 10 refers to 3. I'm saying that there are 3 types of people. Everybody has heard the binary joke

**Comment by rithvikvibhu** [comment]
How about we check the screen width. If there is space include it, else no

**Comment by thel3l** [comment]
Thanks for the response @lunaroyster . But I was looking more for a response like @rithvikvibhu 's.
