### ISSUE TITLE
Logo is messed up.

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#22]
If we could fix it without changing everything else
...

**Comment by thebongy** [comment]
Put a `font-size` style rule in the `.text` class in the css and adjust the value to your needs. 150 px should do it I think.
`.text {
      font-size:150px;
}
`

**Comment by lunaroyster** [comment]
Thanks!!! That worked. But it looks different from what it did. 
But it will do for now. I'm sure some overwriting happened.

**Comment by thebongy** [comment]
@lunaroyster  can you check out https://github.com/thel3l/hackathon-dpse/pull/20 ?

**Comment by thel3l** [comment]
@thebongy Will do. Just that there are conflicting changes, so we have to manually merge.
