### ISSUE TITLE
1337 and n00b toggle switch. 

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#24]
The toggle to change to 1337 mode is hidden on mobile when in portrait mode.

**Comment by lunaroyster** [comment]
Intentional. No one on mobile uses the terminal. You said it your self

**Comment by lunaroyster** [comment]
See debefcffd1972696984c968a6427dfab2e2cc9d4

**Comment by thel3l** [comment]
True. I never gave them an option. But we might need to fix it if I set up a virtual keyboard so that they can type on a phone.

**Comment by thel3l** [comment]
Closing for now.
