### ISSUE TITLE
Mobile version not consistent over views. 

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#25]
The mobile version only appears when in portrait mode. When rotated to landscape, the website displayed is the normal desktop version.

**Comment by lunaroyster** [comment]
It's based on size. There isn't a mobile version per se.

If the screen can accommodate everything without breaking, we show the same page. the sidemenu appears when there is little room to accommodate it

**Comment by thel3l** [comment]
Not really the point. It looks terrible. We need to remove the joke. It takes up to much space.

**Comment by thel3l** [comment]
Or meh.

**Comment by lunaroyster** [comment]
I did it. The joke disappears at 480px. But I think it should go earlier. Will fix that.
