### ISSUE TITLE
Need to remake signup screen

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#26]
I'll do it

**Comment by thel3l** [comment]
What?

**Comment by lunaroyster** [comment]
Signup

**Comment by thel3l** [comment]
I made a new screen for the sign up @lunaroyster @rithvikvibhu .  I need to wait for gh-pages to update, but I'm now going to removed the sign up from the main page.

**Comment by lunaroyster** [comment]
I see we are not doing that anymore
