### ISSUE TITLE
The active menu does not work in mobile.

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#27]

**Comment by rithvikvibhu** [comment]
Will work on this after studying for a while

**Comment by thebongy** [comment]
What exactly is not working?

**Comment by thebongy** [comment]
I think it does work, just that the home link is not activating, everything else is....... well that should be an easy solve.

**Comment by rithvikvibhu** [comment]
The #3 doesn't work on mobile

**Comment by thebongy** [comment]
![screenshot_2015-10-16-20-15-33](https://cloud.githubusercontent.com/assets/7080652/10544798/123cac2a-7443-11e5-98ec-7c14fcbb6dd6.png)
You mean this? It changes right?

**Comment by rithvikvibhu** [comment]
Doesn't work on chrome dev Android and come beta Android. And it seems not only for me

**Comment by lunaroyster** [comment]
Not on chrome mobile emulator either

**Comment by thebongy** [comment]
@ritvikvibhu which phone and version of Android are you using?

**Comment by thel3l** [comment]
@thebongy xD He's using Android 6.0 Dev Preview on a Nexus 4.

**Comment by rithvikvibhu** [comment]
:) but also confirmed on 5.0 and 5.1.1

**Comment by thel3l** [comment]
That's because he will **_never**_ get a Marshmallow OTA.

**Comment by rithvikvibhu** [comment]
@thel3l that is why I have got the PURE AOSP (not cm) before ur opo. ☺

**Comment by rithvikvibhu** [comment]
Currently works only when in section 4 and 5. Not for the first 3 sections.

**Comment by thebongy** [comment]
A possible solution would be to increase the value in the end of line 114 of responsivenav.js to 200. Not entirely sure, did not test, but this could solve the problem....

**Comment by thebongy** [comment]
I just verified it, changing the value to 250 makes it work with almost all viewport widths

**Comment by thebongy** [comment]
@rithvikvibhu @thel3l  does it work on your phones now? Cause i am not completely sure with the value to be entered there, just estimated. Might need further tinkering.

**Comment by rithvikvibhu** [comment]
@thebongy the home, event and FAQ sections all mark the "home" as active. section 4 and 5 work normally

**Comment by thebongy** [comment]
@rithvikvibhu  is this after applying the fix i posted?

**Comment by rithvikvibhu** [comment]
Before the fix, there was no active element when in first 3 sections. Now Home is always active.

**Comment by thebongy** [comment]
@rithvikvibhu  home is active even if viewport is scolled down to section 2,3, or 4?

**Comment by rithvikvibhu** [comment]
not 2,3,4. 1,2,3

**Comment by thebongy** [comment]
@rithvikvibhu you are using a nexus 4 right?

**Comment by rithvikvibhu** [comment]
yup

**Comment by thebongy** [comment]
for now we can ignore the FAQ section right cause it is empty, right?

**Comment by thebongy** [comment]
or wait sorry misunderstood it. it has stuff...

**Comment by thebongy** [comment]
@rithvikvibhu this should work, unless its a nexus 4 specific browser issue.

**Comment by rithvikvibhu** [comment]
Finally, working.
