### ISSUE TITLE
Need to remove BS from all over.

### ISSUE THREAD

**Issue by rithvikvibhu** [thel3l/hackathon-dpse#28]
If we are going to start advertising soon, we neeeeeed to

**Comment by thel3l** [comment]
On it.

**Comment by rithvikvibhu** [comment]
Any progress?
I can't check from my phone

**Comment by rithvikvibhu** [comment]
@lunaroyster can you confirm its been removed from all commands? Can't do it from a phone here.

**Comment by rithvikvibhu** [comment]
Confirmed no bs

**Comment by lunaroyster** [comment]
You never know...

**Comment by thel3l** [comment]
_sniff_
