### ISSUE TITLE
Active Navbar tab doesn't change when scrolling to a different section

### ISSUE THREAD

**Issue by rithvikvibhu** [thel3l/hackathon-dpse#3]
Home tab is always active even when scrolling down the page

**Comment by rithvikvibhu** [comment]
umm, what exactly did u reference @lunaroyster ?

**Comment by thel3l** [comment]
@lunaroyster You're saying that the spaces were the problem?

**Comment by lunaroyster** [comment]
Nah. Nevermind. Didn't know that hashes opened issues. Whenever I have to adjust space, i make a Space # comnmit. Done it thrice so far...

**Comment by lunaroyster** [comment]
Yeah this is an issue. Removing active tag for now. Fix and add back yea?

**Comment by lunaroyster** [comment]
Found some code on the template I used a while back
// Bind to scroll
$(window).scroll(function(){
   // Get container scroll position
   var fromTop = $(this).scrollTop()+topMenuHeight;

   // Get id of current scroll item
   var cur = scrollItems.map(function(){
     if ($(this).offset().top < fromTop)
       return this;
   });
   // Get the id of the current element
   cur = cur[cur.length-1];
   var id = cur && cur.length ? cur[0].id : "";

   if (lastId !== id) {
       lastId = id;
       // Set/remove active class
       menuItems
         .parent().removeClass("active")
         .end().filter("[href=#"+id+"]").parent().addClass("active");
   }  
});

}

**Comment by rithvikvibhu** [comment]
doesnt work, already tried

**Comment by thebongy** [comment]
Wrote some jquery, check out https://github.com/thel3l/hackathon-dpse/pull/20 .
