### ISSUE TITLE
Everything is broken. (Suspect: Javascript is broken)

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#30]

**Comment by thebongy** [comment]
well console errors show an error with the countdown function in misc.js

**Comment by lunaroyster** [comment]
Yup. We decided to merge all JS to reduce HTTP requests. Guess it wasn't carried out properly...

**Comment by thebongy** [comment]
@lunaroyster why are you risking request times by using more modules? A simple job like a countdown can be easily implemented in a few lines of js. I find the module to have a lot of uneccesary code, so why not write a few lines of countdown code, would barely take any time.....

**Comment by lunaroyster** [comment]
Left all JS to @rithvikvibhu 

Now we know who's gonna fix it...

**Comment by thel3l** [comment]
xD

**Comment by rithvikvibhu** [comment]
Woah woah wait. What's not working?

**Comment by rithvikvibhu** [comment]
Ahhh. It seems there is something wrong with my pushing from PocketGit Android. Haven't nt pushed the latest working commit

**Comment by rithvikvibhu** [comment]
23ff2bb71a355c5f0756ba482aee89f6e760135d

**Comment by thebongy** [comment]
I think the countdown() function was renamed to Countdown() in the new CDN.
