### ISSUE TITLE
How about a Rule Booklet in Java?

### ISSUE THREAD

**Issue by thebongy** [thel3l/hackathon-dpse#31]
Well I think in terms of popularity Java is surely one the first languages that comes to my mind.....

**Comment by thel3l** [comment]
NEVER. **_NEVER.**_

**Comment by lunaroyster** [comment]
That bias tho

**Comment by thel3l** [comment]
**_NO.**_

**Comment by thebongy** [comment]
Well, any reason or.....

**Comment by rithvikvibhu** [comment]
Ys. Because it's java.

**Comment by thebongy** [comment]
Cmon its like there is a booklet for go, but not for java?

**Comment by thebongy** [comment]
Well we should have one 'because it's java'.

**Comment by thel3l** [comment]
Look. Go, Perl, C, Python and Bash we did because **_they're decent**_ languages. Java ( retching noises).
We should NOT have one in Java. @rithvikvibhu Bad experiences.

**Comment by rithvikvibhu** [comment]
Nope. https://lh3.googleusercontent.com/proxy/B8xQQcWE6FRmfTG20hYyE7LA1pPECtkvO0PZOjqhoWsxkZLsjc-MhGvGVzj87jFHQr_2rZ863p6ViKoejw5JNE1K4QtxZw=w353-h417-nc

**Comment by thel3l** [comment]
xD

**Comment by thebongy** [comment]
Since its a public event, analysing public data might be more relevant. www.tiobe.com/index.php/content/paperinfo/tpci/index.html

**Comment by thebongy** [comment]
Since its a public event, analysing public data might be more relevant. www.tiobe.com/index.php/content/paperinfo/tpci/index.html

**Comment by thel3l** [comment]
@thebongy 
Stop. Please. We all **_hate**_ Java.

**Comment by thel3l** [comment]
And we already have 3 "top" langs.
