### ISSUE TITLE
Sign up button inactive

### ISSUE THREAD

**Issue by rithvikvibhu** [thel3l/hackathon-dpse#34]
The sign up button doesn't do anything. Thinking it hasn't been linked.

**Comment by rithvikvibhu** [comment]
Related to #26

**Comment by rithvikvibhu** [comment]
533a640ce10628b69628809cbdb5e7334c90ceaa
(Brought back old sign up form)

**Comment by rithvikvibhu** [comment]
@lunaroyster can u css make up a bit? Looks (a bit) ugly

**Comment by lunaroyster** [comment]
It works and doesn't seem to break in mobile
