### ISSUE TITLE
Do we need mercurial?

### ISSUE THREAD

**Issue by rithvikvibhu** [thel3l/hackathon-dpse#37]
Git is going to be enough I think. we'll mostly be using school computers and running a lot of stuff might be a problem. Especially if the event is going to be big and every team and member will have an account

**Comment by lunaroyster** [comment]
Yup. Getting the current participants to all use a local git server is quite a challenge already

**Comment by rithvikvibhu** [comment]
@lunaroyster you mean no. read the question. xD

**Comment by lunaroyster** [comment]
ha. I said yup after reading the description, not the question.

**Comment by lunaroyster** [comment]
Obviously, all participants can use anything. Hell, they can use pendrives to move files around. But we provide git support, as opposed to both git and mercurial.

**Comment by thel3l** [comment]
Ook. We run a Github Enterprise Server on the event day.
