### ISSUE TITLE
Rules and/or requirements for candidates. Where do we put them?

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#38]
On the same page (index.htm) or different?

**Comment by rithvikvibhu** [comment]
Maybe send a mail with rules to those who registers on website?

**Comment by lunaroyster** [comment]
Makes sense. We begin on that when we get a few registrations

**Comment by rithvikvibhu** [comment]
So this question stays open?

**Comment by rithvikvibhu** [comment]
Closing inactive issue
