### ISSUE TITLE
ReCaptcha isn't set up yet

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#43]
@rithvikvibhu Set it up?

**Comment by thel3l** [comment]
It's working.

**Comment by lunaroyster** [comment]
It's not. It doesn't verify with google. I currently don't need to use it to be able to click the "I'm in" Button

**Comment by lunaroyster** [comment]
In Short: Server side is not integrated.

**Comment by thel3l** [comment]
Aah.

**Comment by lunaroyster** [comment]
Hyperactive.

**Comment by rithvikvibhu** [comment]
lel. totally forgot about it. on it.

**Comment by rithvikvibhu** [comment]
buy does the normal registration work? with the email and activation?

**Comment by lunaroyster** [comment]
lemme try

**Comment by thel3l** [comment]
I'm doing it.

**Comment by thel3l** [comment]
Oh lel. @rithvikvibhu  @lunaroyster  You guys doing it?

**Comment by lunaroyster** [comment]
I don't get the email

**Comment by rithvikvibhu** [comment]
Set up now. No commit to refer to as changes made only on the server side.
