### ISSUE TITLE
Lack of Error/Confirmation message makes user think nothing has happened (in signup)

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#45]

**Comment by rithvikvibhu** [comment]
hmmm?
when and where?

**Comment by thel3l** [comment]
Fixing.

**Comment by rithvikvibhu** [comment]
Ahhh. the only thing it currently does is disable all fields and button

**Comment by thel3l** [comment]
Partial fix with b50a03614f1047f2c3966f1fcb655080b52c9876

**Comment by rithvikvibhu** [comment]
NOOOOO. that message required is "Please wait..."

**Comment by thel3l** [comment]
I said partial. And in Slack, I said " I made a mistake

**Comment by thel3l** [comment]
Hmm. Slight Q here. The sign up is instant. Which means that having the alert in

``` js
        request.always(function () {
```

makes sense.

**Comment by rithvikvibhu** [comment]
isn't that what u have done? @thel3l It should be there

**Comment by thel3l** [comment]
f0dc8a960aa4ed063db4714e6a5d85e96eb62605

**Comment by rithvikvibhu** [comment]
Exactly. that's fine

**Comment by rithvikvibhu** [comment]
Finally, a working thing 2455d8b73d6ce8f37938df80581176c1f9af0a8b

**Comment by lunaroyster** [comment]
There's an error message that shows up. Also, no email

**Comment by rithvikvibhu** [comment]
Uhhh. Did u refresh the page?
