### ISSUE TITLE
Page broken on devices with extra large screens

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#46]
https://github.com/Rahultarak/spark-change/commit/3f26bff352c083e24949abc864670225b012fd30

**Comment by rithvikvibhu** [comment]
Hmmm. Does it matter?

Schools don't give presentations on big screens like TVs and wiht projectors.

**Comment by lunaroyster** [comment]
That large screen happens to be a mac

**Comment by lunaroyster** [comment]
Not large. High resolution

**Comment by thel3l** [comment]
Retina Display (s).

**Comment by rithvikvibhu** [comment]
Ahhh. Will check later
