### ISSUE TITLE
Seriously, Javascript Alerts look ugly.

### ISSUE THREAD

**Issue by thebongy** [thel3l/hackathon-dpse#47]
The alerts seriously by themselves are ugly, and they anyway dont match with the page at all. Might I suggest, something more better on the eyes, like https://t4t5.github.io/sweetalert/

**Comment by rithvikvibhu** [comment]
Hmmm. Looks naice. Look into someone later this evening

**Comment by lunaroyster** [comment]
Got the library in. Will integrate later

**Comment by rithvikvibhu** [comment]
i Hereby declare this issue closed.
