### ISSUE TITLE
The markup isnt dirty, its the point of a min.js file!

### ISSUE THREAD

**Issue by thebongy** [thel3l/hackathon-dpse#48]
5c133496fe441064498d5fd14154271a55ef23c8 . Why define the markup? Its not like you are going to make changes in the library itself. The point of a min file is to minimize on all white space, thus reducing file size, and thus leading to better loading speeds. In the end of development, all your js files should be integrated into one and then minified (remove white space) as this can lead to **much smaller file sizes**.

**Comment by lunaroyster** [comment]
So we can read through the code (for now). We'll compress it later...

**Comment by thebongy** [comment]
Oh, Ok
