### ISSUE TITLE
The colour of the login page 

### ISSUE THREAD

**Issue by hackdpse** [thel3l/hackathon-dpse#49]
We need to change the colour of the login page and fix the "confirm password"

**Comment by thel3l** [comment]
This is two different issues...

**Comment by thel3l** [comment]
This is two different issues...

**Comment by rithvikvibhu** [comment]
Lel. Doesn't matter. I still get #50 !!!!

**Comment by thel3l** [comment]
_facepalm_

**Comment by rithvikvibhu** [comment]
Die.

**Comment by lunaroyster** [comment]
Ain't there be no signup no more. (We got a better signup integrated)
