### ISSUE TITLE
DPSE Codefest logo

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#5]
Got the svg text animation working. Now. We need a proper name.

**Comment by rithvikvibhu** [comment]
meh

**Comment by rithvikvibhu** [comment]
what name exactly?

**Comment by thel3l** [comment]
Codefest or hackathon?

**Comment by rithvikvibhu** [comment]
i vote CodeFest officially, but use hackathon while spreading and discussing

**Comment by lunaroyster** [comment]
Codefest. dpse.cf afterall

**Comment by thel3l** [comment]
Done.
