### ISSUE TITLE
HTTPS requests to someone named @rithvikvibhu?

### ISSUE THREAD

**Issue by rithvikvibhu** [thel3l/hackathon-dpse#50]
WHY Does the server contact @rithvikvibhu 's VM to send emails?

**Comment by rithvikvibhu** [comment]
Fixing it :P

**Comment by rithvikvibhu** [comment]
Fixed. All mails now sent from CodeFest VM

**Comment by rithvikvibhu** [comment]
BTW. I created the 50th issue :keycap_ten: \* 5 = 50

P.S. I'm bored.

**Comment by thel3l** [comment]
You suffer from a double personality disorder..

**Comment by rithvikvibhu** [comment]
Yay for me.
