### ISSUE TITLE
MAJOR ISSUE. BREAKS EVERYTHING - the word git is blue. 

### ISSUE THREAD

**Issue by lunaroyster** [thel3l/hackathon-dpse#56]
THE DAMN GIT LINK IS TOO HARD TO READ. MAH AYEEEESS THEY BE BLEEDING

**Comment by thel3l** [comment]
XD 
DROP THE CAPS! MY EYES HURT. WILL FIX. ITS NOT ALL THAT BAD!

**Comment by rithvikvibhu** [comment]
OH GAWD. 2012 ALL OVER AGAIN

**Comment by thel3l** [comment]
AAaaghhg!

**Comment by rithvikvibhu** [comment]
Webhook not working. Switched back to cron job. Works as expected. Purged cloudflare cache

Just for info,
VM pulls every minute
Cloudflare caches for 2 hours.
Browsers (clients) are instructed to cache for 1 to 2 hours.

So if u commit something it will take a maximum of 4 hours (not 6) to display on dpse.cf
