### ISSUE TITLE
Loading screen.

### ISSUE THREAD

**Issue by thel3l** [thel3l/hackathon-dpse#9]
We need a loading screen for the site. It's getting a bit painful to wait.

**Comment by rithvikvibhu** [comment]
Code already in another branch site-templates

**Comment by thel3l** [comment]
Hm. Was thinking of a more customised one.

**Comment by lunaroyster** [comment]
> Hm. Was thinking of a more customised one.

HAHA Yeah.

**Comment by lunaroyster** [comment]
Done. Will add spinner later, but the loading screen is done.
